#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo -e "\e[101m\e[97m============================================\e[39m\e[49m"
    echo -e "\e[101m\e[97m== Please do not run as root/super user!  ==\e[39m\e[49m"
    echo -e "\e[101m\e[97m============================================\e[39m\e[49m"
fi